server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # NÃO deixar JSON cair no SPA
    location ~* \.json$ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 7d;
        add_header Cache-Control "public";
    }

    location = /index.html {
        add_header Cache-Control "no-store";
    }
}